name: Run RSpec tests
on: [pull_request]
jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.5.5
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
      - name: Add code coverage comment
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov/simplecov-reports.lcov
          github-token: ${{ github.token }}
          filter-changed-files: true
          delete-old-comments: true
