name: Run RSpec tests
on: [pull_request]
jobs:
  run-simplecov-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.5.5
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: head-result
          path: coverage/.resultset.json
  build-base:
    name: "Build base"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ## Here we do not checkout the current branch, but we checkout the base branch.
          ref: ${{ github.base_ref }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run test
        run: bundle exec rspec
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: base-result
          path: coverage/.resultset.json
  compare:
    name: "Compare base & head coverages"
    runs-on: ubuntu-latest
    needs: [build-base, build-head]

    steps:
      - name: Download base artifact
        uses: actions/download-artifact@v1
        with:
          name: base-result

      - name: Download head artifact
        uses: actions/download-artifact@v1
        with:
          name: head-result

      - uses: kzkn/simplecov-resultset-diff-action@v1
        with:
          base-resultset-path: ./base-result/.resultset.json
          head-resultset-path: ./head-result/.resultset.json
          token: ${{ github.token }}
