name: Run RSpec tests
on: [pull_request]
jobs:
  run-simplecov-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.5.5
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ github.token }}
